[switches]
SWKSOPHZAUD01

[switches:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=XXXXXXXX
ansible_password=XXXXXXX
# ansible_become=yes
# ansible_become_method=enable
# ansible_become_password=YOUR_ENABLE_PASSWORD